import styles from './Layout.module.css';
import React from 'react';

import Head from 'next/head';

interface Props {
  children?: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        created by <a href='#'>leandrogtabak</a> - devChallenges.io
      </footer>
    </div>
  );
};

export default Layout;
